name = "school-telegram-bot"
main = "src/worker.js"
compatibility_date = "2025-09-17"

# Привязка KV (создадим Namespace после деплоя и вставим id)
[[kv_namespaces]]
binding = "KV_BOT"
id = ""          # вставь ID после создания namespace в Cloudflare
preview_id = ""  # можно оставить пустым

[vars]
PUBLIC_URL = ""  # после первого деплоя укажи https://<имя>.workers.dev
